name: NPM API Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Gradle Release"]
    types:
      - completed

jobs:
  call-workflow:
    uses: Forsakringskassan/.github/.github/workflows/api-npm-release.yaml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}