name: NPM API Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  call-workflow:
    uses: Forsakringskassan/.github/.github/workflows/api-npm-release.yaml@4a0ffca
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}