name: Publish release on tag push

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Gradle Release"]
    types:
      - completed

jobs:
  call-release:
    uses: Forsakringskassan/.github/.github/workflows/publish-release-on-tag-push.yaml@main